### PR TITLE
Fixed a reported race condition in conn.go

### PR DESCRIPTION
**Pull request by MarkSonghurst**
As reported by the Go race condition checker.

### CODE REVIEW

**Comment by caledhwa** [comment]
Looks like a good idea +1

Did you run gofmt? Looks like a lot of cleanup of spaces.

**Comment by MarkSonghurst** [comment]
Yes I ran go fmt - I try to make a habit of it :-)

**Comment by caledhwa** [comment]
Good call. I was tempted but didn’t want to make too many updates in my PR that were unrelated. I’d love to see this project get some CI somewhere. However, I haven’t been able to find one that offers a SQL Server service (like TravisCI offers a MongoDB, Postgres, etc). It’d be way cool to get badges such as coverage, and test results, etc. Since it’s all open source it should be free. And we could add a Go Report Card (which would have blessed you for your gofmt update!). Good stuff.

+1 your PR though, just need to get @ianic on it ;-)



On March 4, 2016 at 8:57:41 AM, Mark Songhurst (notifications@github.com) wrote:

Yes I ran go fmt - I try to make a habit of it :-)

**Comment by ianic** [comment]
Thanks Mark.

Did you manage to setup test environment and run gofreetds test locally.
We have pretty good test coverage 88.7%.

**Comment by MarkSonghurst** [comment]
You are welcome.
Sorry, I did not run the test suite I'm afraid, I do not have access to a SQL Server I can install Pubs onto. If one could be made available for contributors of this group, that would be really useful?

**Comment by caledhwa** [comment]
If we are interested... I can look into this

**Comment by MarkSonghurst** [comment]
+1 from me - thanks Cale.

**Pull request merged**
