### PR TITLE
Removing setting login version to allow version to be set from freetds

### PR DESCRIPTION
**Pull request by caledhwa**
dbsetlversion(login, DBVERSION_72);

This line in the conn.go file is forcing the version of the connection to 7.2. If you have a scenario where you need a specific version, this call will override it. In my case, Sybase ASE 16 requires me to use TDS Version 5.0. 

Confirmed that it's overridden by setting up the TDSDUMP file and attempting a connection from ```gofreetds```. 

When this line was commented out, the connection went through (although your starting options are incompatible with ASE 16 so I'll need to work with that as another issue).

Also, it appears my PR updated some lines with trailing spaces - hopefully that is ok.

### CODE REVIEW

**Comment by caledhwa** [comment]
Bump?

**Comment by ianic** [comment]
Thank you for your effort, and sorry for the late answer.

Must say that I never test the gofreetds with Sysbase. And didn't plan to support it.
I decided to force tds version because some features are dependent on the tds protocol version.
Test's are failing if tds protocol version is 4.2, 5.0 or 7.0 (to name a few which I try).
If we remove setting tds version then we are dependent on values in freetds.conf, which can lead to unexpected behviror.

**Comment by caledhwa** [comment]
How about an override?! I could code that up to support both and not break the tests. Maybe I'll give a stab at that, and if it works you could consider.

I think it's actually pretty cool that only one change lead to allowing this to work with Sybase. But I totally understand if you wouldn't want to get wrapped up in that.

**Comment by ianic** [comment]
I'm thinking about adding parameter to the connection string which will make driver work with sysbase. 
For example:
```
   compatibility_mode=sysbase
```
When working in that mode we will set tds version to 5.0, skip setting connection defaults and open space for future sysbase adjustments. 
If compatibility mode is not set we will work in mssql mode, which is current behavior.

What you think about that solution?
Are you willing to change your pull requests in that direction.

Thanks,
Igor.

**Comment by caledhwa** [comment]
This seems like a great idea! Did you see my other pull request then? That's the other issue with Sybase. Setting those default database options on every connection will not allow Sybase to work (mainly because those database options have different names). You could bundle each configuration, or you could simply accept that other pull request.

One last request?

It's spelled "SYBASE" not "SYSBASE"... if you get that correct it will make more sense. But compatibility_mode=sybase seems like a fine idea.

**Comment by ianic** [comment]
Sorry for the spelling. It is obvious that I never used Sybase.

Are you willing to make another pull request which will introduce _compatibility_mode_ connection string parameter and if it is set made adjustments from both current pull requests.

**Comment by caledhwa** [comment]
Surely! It will probably take me a few days. Thanks for the consideration! 



On February 11, 2016 at 2:14:16 AM, Igor Anić (notifications@github.com) wrote:

Sorry for the spelling. It is obvious that I never used Sybase.

Are you willing to make another pull request which will introduce compatibility_mode connection string parameter and if it is set made adjustments from both current pull requests.

**Comment by caledhwa** [comment]
Replaced by PR #31

**Pull request closed without merging**
