### PR TITLE
Using dbdatlen for variable length columns

### PR DESCRIPTION
**Pull request by MarkSonghurst**
A naive fix to get around the 8k limit on varchar(max).
Untested and likely to have issues...!

### CODE REVIEW

**Comment by NoICE** [comment]
I tried this method too, but dbdatlen cannot be known in advance like that. You are defining it in column-checking time. It is 0 for varchar(max) here, because it "canVary". It is known only for primitive types.

I'm currenty trying to move all that dbbind logic to row scanning time, where it seems to know it and where it seems to not care if I call dbbind here too. My light tests are so far successful, I'm currently refactoring it and I need to test it more so I'm sure it behaves how it should.

I'm trying to not to do dbbind for each row and each column (X*Y new ddbind calls :-/) if the canVary is false, so I'm avoiding this new little performance hit when I can.

**Comment by MarkSonghurst** [comment]
Thank you for the clarification, I was wondering why dbdatlen was returning 0 for my populated columns!

**Comment by NoICE** [comment]
Opened #28 . Please try my fork if it fixes things for you. It does for me. I hope I didn't introduce some memory leak or something. But in all my tests it works.

**Comment by NoICE** [comment]
P.S. I didn't touch the part limiting the result to 8k bytes in conn_sp.go, I don't know if that has the same solution as this one.

**Pull request closed without merging**
