### PR TITLE
fix(fetch): don't allocate tons of memory for varchar(max), don't crash on large dbdata

### PR DESCRIPTION
**Pull request by NoICE**
Use freetds's dbdata() for all variable data. Read the data each row.
This fixes both memory allocation of all varchars and crash on size+1,because size now cannot be > int32 for varchar(max), because we don't need to add that +1 now.

### CODE REVIEW

**Comment by NoICE** [comment]
I just discovered a little issue with this. I'll let you know when I find a solution for it.

**Comment by NoICE** [comment]
Okay, the issue was in my code. This pull request is OK.

**Comment by NoICE** [comment]
I really hope I didn't introduce some memory leak. I don't know when freetds frees the memory used by dbdata(). If ever.

**Comment by MarkSonghurst** [comment]
Hi. I tried your fix, but I think it is limited to Result Sets?
I am trying to handle a stored procedure output parameter which is of type varchar(max), unfortunately your fix did not appear to make a difference for me. Thanks for your effort anyway.

**Comment by NoICE** [comment]
Hi, my fix fixes the general usage - running any kind of query. Results from stored procedures are maybe handled a little differently. I hope that my fix will help @ianic to fix stored procedures as well...

**Comment by ianic** [comment]
Great solution.
But there are some failing tests now:
```
--- FAIL: TestExecSpInputParams2 (0.03s)
        Error Trace:    conn_sp_test.go:103
	Error:		Not equal: "" (expected)
			        != " " (actual)

        Error Trace:    conn_sp_test.go:105
	Error:		Not equal: []byte{0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7, 0x8, 0x9, 0xa} (expected)
			        != []byte{0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7, 0x8, 0x9} (actual)

			Diff:
			--- Expected
			+++ Actual
			@@ -1,3 +1,3 @@
			-([]uint8) (len=10 cap=10) {
			- 00000000  01 02 03 04 05 06 07 08  09 0a                    |..........|
			+([]uint8) (len=9 cap=9) {
			+ 00000000  01 02 03 04 05 06 07 08  09                       |.........|
			 }

--- FAIL: TestHandlingNumericAndDecimalDataTypes (0.02s)
        Error Trace:    conn_sp_test.go:176
	Error:		Not equal: 1.25 (expected)
			        != 2.65249474125e-312 (actual)

        Error Trace:    conn_sp_test.go:177
	Error:		Not equal: 1.26 (expected)
			        != 4.9530153897185765e-73 (actual)

        Error Trace:    conn_sp_test.go:178
	Error:		Not equal: 1.27 (expected)
			        != 1.4367748644623998e-188 (actual)

--- FAIL: TestBugGuidInSpParams (0.02s)
        Error Trace:    conn_sp_test.go:211
	Error:		Not equal: "B5A0E32D-3F48-4CC2-A44B-74753D9CACF8" (expected)
			        != "-㠵H?\xc2L\xa4Ktu=\x9c\xac\xf8" (actual)

--- FAIL: TestBlobs (0.02s)
        Error Trace:    mssql_test.go:174
	Error:		Not equal: 16 (expected)
			        != 15 (actual)

        Error Trace:    mssql_test.go:178
	Error:		Not equal: "000102030405060708090a0b0c0d0e0f" (expected)
			        != "000102030405060708090a0b0c0d0e" (actual)

        Error Trace:    mssql_test.go:179
	Error:		Not equal: []byte{0x0, 0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7, 0x8, 0x9, 0xa, 0xb, 0xc, 0xd, 0xe, 0xf} (expected)
			        != []byte{0x0, 0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7, 0x8, 0x9, 0xa, 0xb, 0xc, 0xd, 0xe} (actual)

			Diff:
			--- Expected
			+++ Actual
			@@ -1,3 +1,3 @@
			-([]uint8) (len=16 cap=16) {
			- 00000000  00 01 02 03 04 05 06 07  08 09 0a 0b 0c 0d 0e 0f  |................|
			+([]uint8) (len=15 cap=15) {
			+ 00000000  00 01 02 03 04 05 06 07  08 09 0a 0b 0c 0d 0e     |...............|
			 }

FAIL
exit status 1
FAIL	gofreetds	1.302s
```

I think that the source of this problem is that dbvarylen is returning true for all nullable types too.
Tried to find a way to detect varchar(max) so I replaced:
```
  col.canVary = C.dbvarylen(conn.dbproc, no) == C.DBINT(1)
```
with:
```
   // detecting varchar(max) or varbinary(max) types
   col.canVary = (size == 2147483647 && typ == SYBCHAR) ||
     (size == 1073741823 && typ == SYBBINARY)
```

Now all test are passing, and we can use varchar(max) columns longer than 8000 characters.

**Comment by NoICE** [comment]
Those test failing are interesting. Looks like each test fails just because one byte is missing at the end. But I don't get why. I didn't see any missing characters at the end of the results for queries I tested. Those are SP tests. Results from stored procedures are 1 byte longer? If so, do you know why?

Also the the guid test, which fails completely, is very strange. I don't see how that can happen. Maybe the dbdata returns the guid in it's native byte form? (I.e. as it's stored on the filesystem.) Instead of changing it to string? Or do you convert GUID type to string somewhere else?

**Comment by ianic** [comment]
Don't think that this is related to stored procedures.
There is some special handling of guids: 
```
			if typ == SYBUNIQUE {
				size = 36
			}
```

Did you try to setup test database: https://github.com/minus5/gofreetds#testing

**Pull request merged**
